name: Build package for release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Package
        run: mvn package -DskipTests -Dmaven.javadoc.skip=true
      - name: Get files
        run: cp hdt-java-package/target/hdt-java-package-*.tar.gz rdfhdt.tar.gz
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: rdfhdt.tar.gz
          asset_name: rdfhdt.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
